### ISSUE TITLE
Can't view individual 'help/' and 'done/' pages

### ISSUE THREAD

**Issue by davidbasalla** [alphagov/govuk-toolkit-chrome#40]
When viewing the content item for a specific help page (eg https://www.gov.uk/help/about-govuk) it shows the 'special route' entry for the '/help' slug, but not content item for '/help/about-govuk'.

For done pages (eg https://www.gov.uk/done/pay-dvla-fine), viewing the content item returns a 404.

**Comment by Davidslv** [comment]
@davidbasalla I've have fixed the https://www.gov.uk/done/pay-dvla-fine here: https://github.com/alphagov/govuk-toolkit-chrome/pull/39

Have you updated your plugin recently?
Or are you saying there's still a bug?

**Comment by davidbasalla** [comment]
Ah nice, hadn't seen that, but yeah currently it does not work in my browser. I wasn't aware I had to update the plugin myself? Granted I don't know anything about how Chrome extensions work :/ 

From the code in https://github.com/alphagov/govuk-toolkit-chrome/pull/39 it looks like only 'done' pages are supported. 'help' pages would probably need the same fix?

**Comment by tijmenb** [comment]
Closed via https://github.com/alphagov/govuk-toolkit-chrome/pull/42.
