### ISSUE TITLE
Deeplink to Whitehall

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-toolkit-chrome#74]
We currently link to the admin index page for Whitehall editions. Using the new `/admin/by-content-id` route (https://github.com/alphagov/whitehall/pull/2847) we can link directly.

https://github.com/alphagov/whitehall/blob/master/config/routes.rb#L162

**Comment by rubenarakelyan** [comment]
Solved by https://github.com/alphagov/govuk-toolkit-chrome/pull/88
