### ISSUE TITLE
Scrollbar in window

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-toolkit-chrome#81]
On a page like https://www.gov.uk/education the extension window shows a scrollbar:

<img width="1552" alt="screen shot 2017-10-03 at 10 55 31" src="https://user-images.githubusercontent.com/233676/31119609-704fe7ac-a829-11e7-9521-2f4d48969a9b.png">

**Comment by tomsabin** [comment]
This seems to be only a problem when a page has A/B testing, one solution could be to increase the height of the extension, but unfortunately this seems to be outside of our control. From what I've checked, the maximum dimensions the extension can be is 800px wide and 600px high.

Perhaps we could combine the "A/B test" and "Highlight Components" toggles together instead? https://github.com/alphagov/govuk-toolkit-chrome/pull/84 should resolve this
