### ISSUE TITLE
Make plugin compatible with Firefox

### ISSUE THREAD

**Issue by alextea** [alphagov/govuk-toolkit-chrome#86]
[How to](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)

The [Firefox extension compatibility test](https://www.extensiontest.com/) warns that inline scripts are blocked by default. However this can be unblocked by setting the [content security policy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy) to [allow unsafe inline scripts](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script) by hashing the script content

**Comment by tijmenb** [comment]
I added this to the Firebreak board yesterday - https://trello.com/c/5g5lCG9G

**Comment by rubenarakelyan** [comment]
Solved by https://github.com/alphagov/govuk-toolkit-chrome/pull/90
