### ISSUE TITLE
Merge in some GOV.UK bookmarklets

### ISSUE THREAD

**Issue by dsingleton** [alphagov/govuk-toolkit-chrome#9]
https://github.com/dsingleton/govuk-bookmarklets

I think some of these are in, but some not

**Comment by tijmenb** [comment]
Yes!

I assume the "goto publisher" / "goto panopticon" bookmarks would be the most important?

@elliotcm and I chatted about this a while back. I have been thinking about a way to solve this well. 

Perhaps the best way would be to add predictable URL on each publishing app that redirects to the proper edit page, eg:

https://collections-publisher.publishing.service.gov.uk/goto/7343a693-ff68-4543-ba1e-16bdbc676543
https://whitehall-admin.publishing.service.gov.uk/goto/64dc251c-8545-4f5e-8aef-596abc3ec1a8

To do this we would also need to expose the `publishing_app` in content-store.

Thoughts?

**Comment by elliotcm** [comment]
See also https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/find-in-admin-bookmarklet

At that point you might as well expose the admin link (or the redirect version) since you'd have access to Plek.  It's a bit gross.  Maybe have a "more detail" param so that stuff doesn't clutter up normal API users?

**Comment by elliotcm** [comment]
Also have we made any attempt to shop this around to departments, to make their lives easier?

**Comment by dsingleton** [comment]
I made the 'goto-*publisher*' bookmarklets a while back, mostly for my own use, but a few content designers saw then and copied them. I don't know how widely they're used. I'd check with the content team.

I'm not sure if they're most important, more that we probably shouldn't have two ways of doing these things floating around, and the bookmarklets that don't exist in the extension should be merged in. 

Personally I use `Gov-a-lytics` most, to analytics info like rendering app, which the other values (format, orgs, could be added under.

Exposing the edit URL feels a bit weird, doubly so for a `more detail` param (i thought one of the aims of content store was to avoid parameterisation hell?). Alternatively we could have a single end point that takes a content id and redirects you to the right app - that would avoid needing to alter the content item.

**Comment by elliotcm** [comment]
Parameterisation hell under normal circumstances yes.  A single endpoint seems like a good idea though.

**Comment by tijmenb** [comment]
Closing this, I think most of the bookmarklets have been added now. PRs welcome for additional functionality!
